from typing import Literal

from app.config import get_llm
from app.schemas.models import SpecialistReport


AgentName = Literal[
    "behavior_agent",
    "business_agent",
    "experiment_agent",
]


def ensure_specialist_report(
    result: dict,
    agent_name: AgentName,
) -> SpecialistReport:
    """
    Return a validated SpecialistReport.

    Primary path:
        Use structured_response generated by create_agent.

    Fallback path:
        If the model returned a normal text response,
        use a second lightweight structured-output call
        to convert that response into SpecialistReport.

    The formatter is NOT allowed to introduce new facts
    or perform new calculations.
    """

    # =========================================================
    # Primary structured response
    # =========================================================
    structured_response = result.get(
        "structured_response"
    )

    if structured_response is not None:

        if isinstance(
            structured_response,
            SpecialistReport
        ):
            return structured_response

        return SpecialistReport.model_validate(
            structured_response
        )

    # =========================================================
    # Extract final natural-language response
    # =========================================================
    messages = result.get(
        "messages",
        []
    )

    if not messages:

        raise RuntimeError(
            f"{agent_name} returned neither "
            "structured_response nor messages."
        )

    last_message = messages[-1]

    final_text = getattr(
        last_message,
        "content",
        None
    )

    if not final_text:

        raise RuntimeError(
            f"{agent_name} returned no usable "
            "final response."
        )

    # =========================================================
    # Structured-output fallback
    # =========================================================
    llm = get_llm()

    formatter = llm.with_structured_output(
        SpecialistReport,
        method="function_calling",
        strict=False,
    )

    formatting_prompt = f"""
Convert the following specialist-agent analysis into the
SpecialistReport schema.

The agent_name MUST be:

{agent_name}

IMPORTANT RULES:

1. Do NOT add any new facts.
2. Do NOT perform any new arithmetic.
3. Do NOT invent statistics.
4. Preserve numerical evidence exactly as provided.
5. Preserve limitations and uncertainty.
6. The task is formatting only, not re-analysis.
7. recommendation may be null if the source analysis
   contains no recommendation.

SOURCE ANALYSIS:

{final_text}
"""

    report = formatter.invoke(
        formatting_prompt
    )

    if not isinstance(
        report,
        SpecialistReport
    ):
        report = SpecialistReport.model_validate(
            report
        )

    # Force correct specialist identity.
    report = report.model_copy(
        update={
            "agent_name": agent_name
        }
    )

    return report